name: Build latest snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: sourcesJar
          build-root-directory: java

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: java
