name: Publish latest release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      
      - name: Add nexus credentials
        run:
        - echo "user=${{ secrets.NEXUS_USER }}" > java/gradle.properties
        - echo "password=${{ secrets.NEXUS_PASSWORD }}" >> java/gradle.properties

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean
          build-root-directory: java
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: java

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: java
